#!/usr/bin/env python


import ctypes

libadict_so=ctypes.CDLL('../build/libadict.so')
libadict_so.urand_init()

from run_test import run_test

import test_alist.push_pop_unshift_shift
import test_alist.push_search

if __name__=='__main__':
    print()
    run_test(test_alist.push_pop_unshift_shift,libadict_so)
    run_test(test_alist.push_search           ,libadict_so)


# vim:ts=4:sw=4:et:
